version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: job-pg
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DATABASE=jobapp
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5434:5432'
